USE [master]
GO

/****** Object:  Database [LibraryMgmtSys]    Script Date: 1/21/2018 4:39:04 PM ******/
CREATE DATABASE [LibraryMgmtSys]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibraryMgmtSys', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LibraryMgmtSys.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LibraryMgmtSys_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\LibraryMgmtSys_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LibraryMgmtSys] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryMgmtSys].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibraryMgmtSys] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryMgmtSys] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibraryMgmtSys] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibraryMgmtSys] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibraryMgmtSys] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LibraryMgmtSys] SET  MULTI_USER 
GO

ALTER DATABASE [LibraryMgmtSys] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibraryMgmtSys] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibraryMgmtSys] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibraryMgmtSys] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LibraryMgmtSys] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LibraryMgmtSys] SET  READ_WRITE 
GO

